version: '3.4'

networks:
  demoblazorapp:
volumes:
  sqlsystem:
  sqldata:   
  sqllog:
  sqlbackup:

services:
  demoappdb:
    container_name: demoappdb
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345678x@X
    networks:
      - demoblazorapp
    volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup   
  demoblazorserverapp:
    container_name: demo-blazor-app
    image: microservicesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=12345678x@X
    networks:
      - demoblazorapp